"""Experiment reporting system."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


class ExperimentReport:
    """Generates research-quality experiment reports."""

    def __init__(self, experiment_id: str, reports_dir: str | Path = "reports"):
        self.experiment_id = experiment_id
        self.reports_dir = Path(reports_dir)
        self.reports_dir.mkdir(parents=True, exist_ok=True)
        self.sections: dict[str, str] = {}
        self.metadata: dict[str, Any] = {
            "experiment_id": experiment_id,
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }

    def set_metadata(self, **kwargs) -> None:
        self.metadata.update(kwargs)

    def add_section(self, title: str, content: str) -> None:
        self.sections[title] = content

    def generate_markdown(self) -> str:
        lines = [
            f"# Experiment Report: {self.experiment_id}",
            "",
            f"**Generated:** {self.metadata.get('generated_at', 'unknown')}",
            f"**Experiment ID:** {self.experiment_id}",
            "",
        ]

        if "hypothesis" in self.metadata:
            lines.extend([
                "## Hypothesis",
                "",
                self.metadata["hypothesis"],
                "",
            ])

        if "setup" in self.metadata:
            lines.extend([
                "## Setup",
                "",
                self._dict_to_md(self.metadata["setup"]),
                "",
            ])

        for title, content in self.sections.items():
            lines.extend([
                f"## {title}",
                "",
                content,
                "",
            ])

        if "limitations" in self.metadata:
            lines.extend([
                "## Limitations",
                "",
                self.metadata["limitations"],
                "",
            ])

        if "next_experiment" in self.metadata:
            lines.extend([
                "## Next Experiment",
                "",
                self.metadata["next_experiment"],
                "",
            ])

        lines.extend([
            "---",
            f"*Report generated by Model Trajectory Research System*",
        ])

        return "\n".join(lines)

    def save(self) -> Path:
        report_path = self.reports_dir / f"{self.experiment_id}.md"
        report_path.write_text(self.generate_markdown(), encoding="utf-8")

        meta_path = self.reports_dir / f"{self.experiment_id}_metadata.json"
        meta_path.write_text(json.dumps(self.metadata, indent=2, default=str), encoding="utf-8")

        return report_path

    def _dict_to_md(self, d: dict, indent: int = 0) -> str:
        lines = []
        for k, v in d.items():
            if isinstance(v, dict):
                lines.append(f"{'  ' * indent}- **{k}:**")
                lines.append(self._dict_to_md(v, indent + 1))
            elif isinstance(v, list):
                lines.append(f"{'  ' * indent}- **{k}:** {', '.join(str(x) for x in v)}")
            else:
                lines.append(f"{'  ' * indent}- **{k}:** {v}")
        return "\n".join(lines)
